### ISSUE TITLE
Error when trying to call using npx command

### ISSUE THREAD

**Issue by vtt-lair** [ghost-fvtt/foundry-publish#311]
As per our quick Discord chat, I'm getting an error when trying to publish to Foundry VTT.

I'm using the following in my yaml:
```
    # Publish to FoundryVTT
    - name: Publish to Foundry VTT Repo
      id: publish_foundry_repo
      run: npx @ghost-fvtt/foundry-publish
      env:
        FVTT_MANIFEST_PATH: 'module.json'
        FVTT_PACKAGE_ID: ${{ secrets.PACKAGE_ID  }}
        FVTT_USERNAME: ${{ secrets.FOUNDRY_ADMIN_USER  }}
        FVTT_PASSWORD: ${{ secrets.FOUNDRY_ADMIN_PW }}
```

And getting the following error:
![image](https://user-images.githubusercontent.com/33215552/196285209-c8007b77-0caf-4f48-a86d-7a2e9af46b11.png)

Not sure I've i'm missing something on my side, or if there is something wrong.

Thanks for this awesome package!
