### ISSUE TITLE
Grab FVTT_PACKAGE_ID from manifest.

### ISSUE THREAD

**Issue by MrVauxs** [ghost-fvtt/foundry-publish#792]
It would be nice to be able to not have to edit the variables for every module by having the default value by whatever is inside the `module.json`, much like how other attributes are defaulted to.

i.e. to have everything you need to have a package published being:
```yaml
- name: Publish to Foundry VTT Repo
              if: ${{ !github.event.release.prerelease }}
              id: publish_foundry_repo
              run: npx @ghost-fvtt/foundry-publish
              env:
                  FVTT_MANIFEST_PATH: "module.json"
                  FVTT_USERNAME: ${{ secrets.FOUNDRY_ADMIN_USERNAME }}
                  FVTT_PASSWORD: ${{ secrets.FOUNDRY_ADMIN_PASSWORD }}
                  FVTT_MANIFEST_URL: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/module.json
```
